#
# Binding is required for `make bundle` to detect that
# the service account yaks-operator requires these
# associated permissions
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yaks-operator-olm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yaks-operator
subjects:
- kind: ServiceAccount
  name: yaks-operator
