# ---------------------------------------------------------------------------
# Copyright the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

config:
  runtime:
    env:
      - name: CITRUS_CAMELK_MAX_ATTEMPTS
        value: 100
      - name: CITRUS_CAMELK_DELAY_BETWEEN_ATTEMPTS
        value: 1000
      - name: CITRUS_CAMELK_AUTO_REMOVE_RESOURCES
        value: false
      - name: CITRUS_KAMELETS_AUTO_REMOVE_RESOURCES
        value: false
    settings:
      loggers:
      - name: INTEGRATION_STATUS
        level: INFO
      - name: INTEGRATION_LOGS
        level: INFO
    resources:
    - hello-source.kamelet.yaml
    - timer-to-log.groovy
    - hello-to-log-binding.yaml
post:
  - name: print dump
    if: env:CI=true && failure()
    run: kamel dump
